version: '3'
services:
  my-app-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    #image: node:alpine
    volumes: 
    - /app/node_modules
    - .:/app
    ports:
      - "3000:3000"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: npm run test
